openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9

tags:
  - name: "TimeSheet"
  - name: "TeamMember"
  - name: "Report"
  - name: "Project"

paths:
  /teammember:
    get:
      summary: This gets all teammembers
      description: This method return list of TeamMembers
      tags:
        - "TeamMember"
      operationId: getTeamMembers
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TeamMemberDTO'
        "400":
          description: BAD REQUEST
        "401":
          description: UNAUTH


    post:
      summary: This method create Teammember
      tags:
        - "TeamMember"
      operationId: insertTeamMember
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TeamMemberDTO'
      responses:
        "201":
          description: CREATED
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TeamMemberDTO'
        "400":
          description: BAD REQUEST
        "403":
          description: FORBIDDEN

    put:
      summary: This method update exist Teammember
      tags:
        - "TeamMember"
      operationId: updateTeamMember
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TeamMemberDTO'
      responses:
        "200":
          description: SUCCESS
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TeamMemberDTO'
        "400":
          description: BAD REQUEST
        "403":
          description: FORBIDDEN
        "404":
          description: NOT FOUND


  /teammember/{teammemberid}:
    get:
      parameters:
        - in: path
          name: teammemberid
          required: true
          schema:
            type: integer
      summary: This method return one Teammember by id if exist
      tags:
        - "TeamMember"
      operationId: getTeamMember
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TeamMemberDTO'
        "400":
          description: BAD REQUEST
        "401":
          description: UNAUTH
        "404":
          description: NOT FOUND

    delete:
      parameters:
        - in: path
          name: teammemberid
          required: true
          schema:
            type: integer
      summary: This method delete one Teammember by id if exist
      tags:
        - "TeamMember"
      operationId: deleteTeamMember
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TeamMemberDTO'
        "400":
          description: BAD REQUEST
        "401":
          description: UNAUTH
        "404":
          description: NOT FOUND
  /report:
    post:
      summary: This method generates requested reports
      description: This method return list of reports that fits given paramenthers
      tags:
        - "Report"
      operationId: getRequiredReports
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReportFilterDTO'
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TimeSheetEntryDTO'
        "400":
          description: BAD REQUEST
        "401":
          description: UNAUTH

  /project:
    get:
      summary: This gets all projects
      description: This method return list of Projects
      tags:
        - "Project"
      operationId: getAllProjects
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProjectDTO'
        "400":
          description: BAD REQUEST
        "401":
          description: UNAUTH


    post:
      summary: This method create Project
      tags:
        - "Project"
      operationId: insertProject
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProjectDTO'
      responses:
        "201":
          description: CREATED
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectDTO'
        "400":
          description: BAD REQUEST
        "403":
          description: FORBIDDEN

    put:
      summary: This method update exist Project
      tags:
        - "Project"
      operationId: updateProject
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProjectDTO'
      responses:
        "200":
          description: SUCCESS
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectDTO'
        "400":
          description: BAD REQUEST
        "403":
          description: FORBIDDEN
        "404":
          description: NOT FOUND

  /project/filter:
    get:
      summary: This method filters projects by name
      description: This method return list of Projects
      tags:
        - "Project"
      operationId: filterProjectsByName
      parameters:
        - in: query
          name: keyword
          schema:
            type: string
          description: Beginning of the name for filter
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProjectDTO'
        "400":
          description: BAD REQUEST
        "401":
          description: UNAUTH


  /project/{projectid}:
    get:
      parameters:
        - in: path
          name: projectid
          required: true
          schema:
            type: integer
      summary: This method return one Project by id if exist
      tags:
        - "Project"
      operationId: getProject
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectDTO'
        "400":
          description: BAD REQUEST
        "401":
          description: UNAUTH
        "404":
          description: NOT FOUND

    delete:
      parameters:
        - in: path
          name: projectid
          required: true
          schema:
            type: integer
      summary: This method delete one Project by id if exist
      tags:
        - "Project"
      operationId: deleteProject
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectDTO'
        "400":
          description: BAD REQUEST
        "401":
          description: UNAUTH
        "404":
          description: NOT FOUND

components:
  schemas:

    TeamMemberDTO:
      description: This is the TeamMember object.
      type: object
      properties:
        id:
          description: The id of TeamMember
          type: integer
        name:
          description: The name of TeamMember
          type: string
        username:
          description: The username of TeamMember
          type: string
        email:
          description: The email of TeamMember
          type: string
        status:
          description: The status of TeamMember
          type: boolean
        hoursPerWeek:
          description: The hours per week of TeamMember
          type: number
      required:
        - name
        - username
        - email

    TimeSheetEntryDTO:
      description: This is an object that represents one user entry
      type: object
      properties:
        id:
          description: The id of the entry
          type: integer
        date:
          description: The date of user entry
          type: string
        description:
          description: The description of user entry
          type: string
        totalTimeSpent:
          description: Total time user entered, including overtime
          type: number
        projectName:
          description: Name of the project on which time is spent
          type: string
        categoryName:
          description: Name of the category where time is spent
          type: string
        teamMemberName:
          description: Name of team member that made the entry
          type: string

    ReportFilterDTO:
      description: This object represents parameters for entry filter
      type: object
      properties:
        startDate:
          description: Beginning of time range
          type: string
        endDate:
          description: End of time range
          type: string
        categoryId:
          description: The category of wanting entries
          type: integer
        projectId:
          description: The project on which time was spent
          type: integer
        teamMemberId:
          description: The team member that made wanted entries
          type: integer
        clientId:
          description: The client for whom the time was spent
          type: integer

    TimeSheetEntryReportDTO:
      description: This is an object that represents one user entry
      type: object
      properties:
        id:
          description: The id of the entry
          type: integer
        date:
          description: The date of user entry
          type: string
        description:
          description: The description of user entry
          type: string
        totalTimeSpent:
          description: Total time user entered, including overtime
          type: number
        projectName:
          description: Name of the project on which time is spent
          type: string
        categoryName:
          description: Name of the category where time is spent
          type: string
        teamMemberName:
          description: Name of team member that made the entry
          type: string

    ProjectDTO:
      description: This is an object that represents one user entry
      type: object
      properties:
        id:
          description: The id of the project
          type: integer
        name:
          description: The name of the project
          type: string
          pattern: ^(?!\s*$).+
        description:
          description: The description of the project
          type: string
        clientId:
          description: The id of the client
          type: integer
        teamMemberId:
          description: The id of the the team member
          type: integer
        status:
          description: The status of the project
          type: string
      required:
        - name
        - status