openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9

tags:
  - name: "TimeSheet"
  - name: "TeamMember"

paths:
  /teammember:
    get:
      summary: This gets all teammembers
      description: This method return list of TeamMembers
      tags:
        - "TeamMember"
      operationId: getTeamMembers
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TeamMemberDTO'
        "400":
          description: BAD REQUEST
        "401":
          description: UNAUTH

    post:
      summary: This method create Teammember
      tags:
        - "TeamMember"
      operationId: insertTeamMember
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TeamMemberDTO'
      responses:
        "201":
          description: CREATED
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TeamMemberDTO'
        "400":
          description: BAD REQUEST
        "403":
          description: FORBIDDEN

    put:
      summary: This method update exist Teammember
      tags:
        - "TeamMember"
      operationId: updateTeamMember
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TeamMemberDTO'
      responses:
        "200":
          description: SUCCESS
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TeamMemberDTO'
        "400":
          description: BAD REQUEST
        "403":
          description: FORBIDDEN
        "404":
          description: NOT FOUND


  /teammember/{teammemberid}:
    get:
      parameters:
        - in: path
          name: teammemberid
          required: true
          schema:
            type: integer
      summary: This method return one Teammember by id if exist
      tags:
        - "TeamMember"
      operationId: getTeamMember
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TeamMemberDTO'
        "400":
          description: BAD REQUEST
        "401":
          description: UNAUTH
        "404":
          description: NOT FOUND

    delete:
      parameters:
        - in: path
          name: teammemberid
          required: true
          schema:
            type: integer
      summary: This method delete one Teammember by id if exist
      tags:
        - "TeamMember"
      operationId: deleteTeamMember
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TeamMemberDTO'
        "400":
          description: BAD REQUEST
        "401":
          description: UNAUTH
        "404":
          description: NOT FOUND


components:
  schemas:

    TeamMemberDTO:
      description: This is the TeamMember object.
      type: object
      properties:
        id:
          description: The id of TeamMember
          type: integer
        name:
          description: The name of TeamMember
          type: string
        username:
          description: The username of TeamMember
          type: string
        email:
          description: The email of TeamMember
          type: string
        status:
          description: The status of TeamMember
          type: boolean
        hoursPerWeek:
          description: The hours per week of TeamMember
          type: number
