openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9

tags:
  - name: "TimeSheet"
  - name: "TeamMember"
  - name: "Client"
  - name: "Report"
  - name: "Country"

paths:
  /teammembers:
    get:
      summary: This gets all teammembers
      description: This method return list of TeamMembers
      tags:
        - "TeamMember"
      operationId: getTeamMembers
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TeamMemberDTO'
        "400":
          description: BAD REQUEST
        "401":
          description: UNAUTH
    post:
      summary: This method creates time sheet entry
      tags:
        - "TimeSheetEntry"
      operationId: insertEntry
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TimeSheetEntryDTO'
      responses:
        "201":
          description: CREATED
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TimeSheetEntryDTO'
        "400":
          description: BAD REQUEST
        "403":
          description: FORBIDDEN
        "404":
          description: NOT FOUND
    put:
      summary: This method changes given time sheet entry
      tags:
        - "TimeSheetEntry"
      operationId: updateEntry
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TimeSheetEntryDTO'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TimeSheetEntryDTO'
        "400":
          description: BAD REQUEST
        "403":
          description: FORBIDDEN
        "404":
          description: NOT FOUND

  /entry/{id}:
    get:
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      summary: This method return one TimeSheetEntry by id if exist
      tags:
        - "TimeSheetEntry"
      operationId: getEntry
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TimeSheetEntryDTO'
        "400":
          description: BAD REQUEST
        "401":
          description: UNAUTH
        "404":
          description: NOT FOUND

    delete:
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      summary: This method delete one Entry by id if exist
      tags:
        - "TimeSheetEntry"
      operationId: deleteEntry
      responses:
        "200":
          description: Success
        "400":
          description: BAD REQUEST
        "401":
          description: UNAUTH
        "404":
          description: NOT FOUND

  /country:
    get:
      summary: This gets all countries
      description: This method return list of countries
      tags:
        - "Country"
      operationId: getCountries
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CountryDTO'
        "400":
          description: BAD REQUEST
    post:
      summary: This method creates Country
      tags:
        - "Country"
      operationId: insertCountry
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CountryDTO'
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CountryDTO'
        "400":
          description: BAD REQUEST
    put:
      summary: This method update exist Country
      tags:
        - "Country"
      operationId: updateCountry
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CountryDTO'
      responses:
        "200":
          description: SUCCESS
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CountryDTO'
        "400":
          description: BAD REQUEST
        "404":
          description: NOT FOUND

  /country/{countryid}:
    get:
      parameters:
        - in: path
          name: countryid
          required: true
          schema:
            type: integer
      summary: Returns Country if exist
      tags:
        - "Country"
      operationId: getCountry
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CountryDTO'
        "400":
          description: BAD REQUEST
        "404":
          description: NOT FOUND
    delete:
      parameters:
        - in: path
          name: countryid
          required: true
          schema:
            type: integer
      summary: Delete country if exist
      tags:
        - "Country"
      operationId: deleteCountry
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                 $ref: '#/components/schemas/CountryDTO'
        "400":
          description: BAD REQUEST
        "404":
          description: NOT FOUND
  /client:
    get:
      summary: This gets all teammembers
      description: This method return list of TeamMembers
      tags:
        - "Client"
      operationId: getClients
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ClientDTO'
        "400":
          description: BAD REQUEST
    post:
      summary: This method creates Client
      tags:
        - "Client"
      operationId: insertClient
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClientDTO'
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientDTO'
        "400":
          description: BAD REQUEST
    put:
      summary: This method update exist Client
      tags:
        - "Client"
      operationId: updateClient
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClientDTO'
      responses:
        "200":
          description: SUCCESS
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientDTO'
        "400":
          description: BAD REQUEST
        "404":
          description: NOT FOUND
  /client/{clientid}:
    get:
      parameters:
        - in: path
          name: clientid
          required: true
          schema:
            type: integer
      summary: Returns Client if exist
      tags:
        - "Client"
      operationId: getClient
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientDTO'
        "400":
          description: BAD REQUEST
        "404":
          description: NOT FOUND
    delete:
      parameters:
        - in: path
          name: clientid
          required: true
          schema:
            type: integer
      summary: Delete client if exist
      tags:
        - "Client"
      operationId: deleteClient
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientDTO'
        "400":
          description: BAD REQUEST
        "404":
          description: NOT FOUND


components:
  schemas:
    TeamMemberDTO:
      description: This is the TeamMember object.
      type: object
      properties:
        id:
          description: The id of TeamMember
          type: integer
        name:
          description: The name of TeamMember
          type: string
          pattern: ^(?!\s*$).+
        username:
          description: The username of TeamMember
          type: string
          pattern: ^(?!\s*$).+
        email:
          description: The email of TeamMember
          type: string
          pattern: ^[A-Za-z0-9+_.-]+@(.+)$
        status:
          description: The status of TeamMember
          type: boolean
        hoursPerWeek:
          description: The hours per week of TeamMember
          type: number
      required:
        - name
        - username
        - email

    ReportFilterDTO:
      description: This object represents parameters for entry filter
      type: object
      properties:
        startDate:
          description: Beginning of time range
          type: string
        endDate:
          description: End of time range
          type: string
        categoryId:
          description: The category of wanting entries
          type: integer
        projectId:
          description: The project on which time was spent
          type: integer
        teamMemberId:
          description: The team member that made wanted entries
          type: integer
        clientId:
          description: The client for whom the time was spent
          type: integer

    CountryDTO:
      description: This object represents parameters for country
      type: object
      properties:
        countryid:
          description: id of country
          type: integer
        name:
          description: name of country
          type: string
        
    ClientDTO:
      description: This is the Client object.
      type: object
      properties:
        id:
          description: Id of client
          type: integer
        name:
          description: Name of client
          type: string
          pattern: ^(?!\s*$).+
        address:
          description: Address of client
          type: string
        city:
          description: City where client lives
          type: string
        zipCode:
          description: Zip code of city where client lives
          type: string
        countryid:
          description: Country id
          type: integer
      required:
        - name

